from .home_view import *
from .log_in_view import *
from .log_out_view import *
from .password_view import *
from .profile_view import *
from .sign_up_view import *
from .recipe_view import *
from .rating_view import *
from .welcome_view import *
from .create_recipe_view import *
from .profile_page_view import *
from .other_user_profile_view import *
from .followers_view import *
from .favourites_view import *
from .delete_recipe_view import *
from .edit_recipe_view import *
