# Generated by Django 5.2.7 on 2026-01-05 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DietaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Username must start with @ and have at least 3 characters.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username must start with @ and have at least 3 characters.', regex='^@\\w{3,}$')]),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine_tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.cuisinetag'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dietary_tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.dietarytag'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
